-- Удаление таблиц в обратном порядке (из-за зависимостей)
DROP TABLE IF EXISTS ship_route CASCADE;
DROP TABLE IF EXISTS document CASCADE;
DROP TABLE IF EXISTS route CASCADE;
DROP TABLE IF EXISTS port CASCADE;
DROP TABLE IF EXISTS ship CASCADE;
DROP TABLE IF EXISTS cargo CASCADE;
DROP TABLE IF EXISTS cargo_type CASCADE;
DROP TABLE IF EXISTS company CASCADE;